name: Build Talal Falcon
on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Theos Environment
        run: |
          sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
          git clone --recursive https://github.com/theos/theos.git ~/theos
          
      - name: Build Tweak
        run: |
          export THEOS=~/theos
          export PATH=$THEOS/bin:$PATH
          make package FINALPACKAGE=1
          
      - name: Upload Finished App
        uses: actions/upload-artifact@v3
        with:
          name: Talal-Falcon-App
          path: packages/*.deb
